### ISSUE TITLE
Feature: User can choose the location that they want weather information about

### ISSUE THREAD

**Issue by dennymin** [dennymin/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to choose where to get information from. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will put an input into a text input

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/127230748-87ec9877-e138-47a5-a207-a38206e456ba.png)
![image](https://user-images.githubusercontent.com/85311223/127230740-db15d464-fc91-4142-8b73-e30f87b6606e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make HTML skeleton
- [x] Link JavaScript and CSS files
- [x] Add background image
- [x] Add floating text background
- [x] Add question
- [x] Add input type text
- [x] Add functionality so that the user can see the input and type it in
- [x] The location that the user inputs is saved into a data model
- [x] Make sure mobile and desktop are compatible
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
