### ISSUE TITLE
Feature: User can select what information they want to see

### ISSUE THREAD

**Issue by dennymin** [dennymin/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see what weather information they want to see.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A checklist of choices of information will be available for the user to check on.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/127374755-1f0db941-30aa-4f7c-bf2b-eaf7674acd42.png)
![image](https://user-images.githubusercontent.com/85311223/127374762-24ceebec-fbcf-436e-b6bb-b2fe470e6ca4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Hide Entry elements
- [x] Create a list of options
- [x] Have the location text emphasized
- [x] Make sure that the text background adjusts size accordingly 
- [x] Include icons for selecting what gets chosen
- [x] Change icons based on what is and what is not being selected
- [x] Allow functionality for each section to be selected
- [x] Save preferences for information in the data model that was created in the first feature
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
