### ISSUE TITLE
Feature: User can see a specific background depending on weather conditions of where they are

### ISSUE THREAD

**Issue by dennymin** [dennymin/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be shown a background with the weather data of the location that they have chosen. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If it is raining, the background will have some sort of rain theme. If it is sunny, a sunnier background will be used.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/127559855-712275f4-24f0-4cb6-a9ea-90ec6ed61c47.png)
![image](https://user-images.githubusercontent.com/85311223/127560070-6d40bbd3-d95f-4062-817d-170eea86f6bb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Display the appropriate background according to weather conditions (only background images are available now)
- [x] Will first check time, then the variable main
- [x] Display time and location prominently always
- [x] Display the information that the user selected
- [x] Use the information that has been saved in the data model
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
