### ISSUE TITLE
Feature: User can have a primary location and multiple saved locations

### ISSUE THREAD

**Issue by dennymin** [dennymin/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set a primary location for the main weather data that they want. They can also be shown information about other data

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have a new banner to use that is activated by the hamburger menu icon. Once clicked, an option for editing locations and changing profile will be present. The user can add new locations or edit previous locations. User can choose which is the primary location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/128091409-17fd3beb-d710-4ed6-a7ae-fd03bc38c274.png)
![image](https://user-images.githubusercontent.com/85311223/128091454-c7f21f22-82db-46e2-95f5-74739c949d05.png)
![image](https://user-images.githubusercontent.com/85311223/128091482-e9e524e3-47c2-4db6-81cf-a48df73e2dca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can now click on hamburger menu for further choices
- [x] The menu will have two options for locations and profile
- [x] Add modal for location options
- [x] Add buttons to make primary location, delete or edit entries, and add new locations
- [x] Save the new locations
- [x] Add functionality so that when a primary location is selected, the page shows the primary location information
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
