### ISSUE TITLE
Feature: User can save their profile

### ISSUE THREAD

**Issue by dennymin** [dennymin/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their profile and be greeted with more personal messages upon using the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can give their name, date of birth, and email address. Upon looking at the main screen, they will be greeted by their first name and then promptly given a light recommendation on what to do based on the weather today or the current time.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/128094276-8e83bd43-aad1-4d8c-ba51-f63dffe87a69.png)
![image](https://user-images.githubusercontent.com/85311223/128094278-4e260769-ad8a-4267-b010-958504a24ad7.png)
![image](https://user-images.githubusercontent.com/85311223/128091655-0f9e4f9a-f46a-4aa6-b3df-28f2b9bf8ee4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Change profile section will open a modal for the user to input information
- [x] User can click on a done button to return to primary weather information
- [x] User will be greeted by first name on main page that uses the profile section
- [x] Recommendation/Greeting will be offered based off of the time and weather
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
